version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: octostore-api
    container_name: octostore-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - octostore-network

  nginx:
    image: nginx:alpine
    container_name: octostore-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - octostore-network

  db:
    image: mysql:8.0
    container_name: octostore-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - octostore-network

  redis:
    image: redis:alpine
    container_name: octostore-redis
    restart: unless-stopped
    networks:
      - octostore-network

networks:
  octostore-network:
    driver: bridge

volumes:
  dbdata:
